version: "3.8"

services: 
  #1. Redis Cache and Message Broker
  redis:
    image: redis:7.2-alpine
    container_name: zenith_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - zenith_network

  #2 PostgreSQL Relational DB
  postgres:
    image: postgres:15-alpine
    container_name: zenith_postgres
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_DB: zenithride
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zenith_network

  #3 Streaming Data Simulator Service
  simulator:
    build: ./simulator
    container_name: zenith_simulator
    environment:
      REDIS_HOST: redis  # Inside Docker, connect to the "redis" container
      DB_HOST: postgres  # Inside Docker, connect to the "postgres" container
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis
      - postgres
    networks:
      - zenith_network
  
  #4 API Gateway Service
  gateway:
    build: ./gateway-service
    container_name: zenith-gateway
    ports:
      - "5000:5000"
    environment: 
      REDIS_HOST: redis
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis
    networks:
      - zenith_network
      
  # 5. Inference Worker Service (Updated to mount shared volume!)
  worker:
    build: ./inference-worker
    environment: 
      REDIS_HOST: redis
      PYTHONUNBUFFERED: 1
    # Mount the shared volume so workers can read model.bin files
    volumes:
      - shared_models:/shared-models
    depends_on:
      - redis
    networks:
      - zenith_network

  # 6. Drift Monitor Service
  monitor:
    build: ./drift-monitor
    container_name: zenith_drift_monitor
    environment: 
      REDIS_HOST: redis
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis
    networks:
      - zenith_network

  training-service:
    build: ./training-service
    container_name: zenith_training_service
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      PYTHONUNBUFFERED: 1
    # Mount the shared volume so trainer can write model.bin files
    volumes:
     - shared_models:/shared-models
    depends_on:
     - redis
     - postgres
    networks:
     - zenith_network

volumes:
  redis_data:
  postgres_data:
  shared_models:

networks:
  zenith_network:
    driver: bridge